-- =============================================
-- GOSPELPLAY - DATOS INICIALES
-- Ejecuta esto en Supabase > SQL Editor
-- DESPUÉS de crear las tablas
-- =============================================

-- ===== MÚSICA =====
INSERT INTO contenido (url, plataforma, titulo, artista, descripcion, duracion, tipo, categoria, genero_musical, es_congregacional, tiene_mensaje, momento_del_culto, energia, nivel, eval_cristocentrico, eval_fidelidad_biblica, eval_profundidad, eval_edificante, eval_doctrina_sana, eval_puntuacion_total, eval_aprobado, eval_notas, pasajes, versiculos_clave, temas, personajes, doctrina, apto_para, audiencia, likes, publicado, revisado_por_ia) VALUES
('https://open.spotify.com/track/ejemplo1', 'spotify', 'Jesús Tú Eres Mi Rey', 'Marcos Witt', 'Adoración congregacional centrada en la soberanía de Cristo', '3:45', 'musica', 'adoracion', 'worship', true, true, 'adoracion_profunda', 'media', 'basico', 95, 90, 80, 92, 95, 90, true, 'Excelente canción cristocéntrica que exalta la soberanía de Cristo.', ARRAY['Apocalipsis 19:16', 'Filipenses 2:9-11'], ARRAY['Apocalipsis 19:16'], ARRAY['soberanía de Cristo', 'adoración', 'reino de Dios'], ARRAY['Jesús'], ARRAY['cristología'], ARRAY['culto dominical', 'grupo pequeño'], ARRAY['todo público'], 2340, true, true),

('https://www.youtube.com/watch?v=ejemplo2', 'youtube', 'Gracia Sublime', 'Bethel Music en Español', 'Adoración profunda sobre la gracia inmerecida de Dios', '5:12', 'musica', 'adoracion', 'worship', true, true, 'adoracion_profunda', 'baja', 'basico', 92, 88, 85, 95, 90, 90, true, 'Canción centrada en la gracia de Dios. Letra teológicamente sólida.', ARRAY['Efesios 2:8-9', 'Romanos 5:8'], ARRAY['Efesios 2:8-9'], ARRAY['gracia', 'salvación', 'amor de Dios'], ARRAY['Jesús'], ARRAY['soteriología'], ARRAY['culto dominical', 'momento de oración', 'devocional personal'], ARRAY['todo público', 'nuevos creyentes'], 1890, true, true),

('https://open.spotify.com/track/ejemplo4', 'spotify', 'Espíritu Santo', 'Kari Jobe', 'Invocación al Espíritu Santo en adoración profunda', '4:28', 'musica', 'adoracion', 'worship', true, true, 'altar', 'baja', 'basico', 85, 88, 78, 92, 90, 87, true, 'Invocación reverente al Espíritu Santo.', ARRAY['Juan 14:26', 'Hechos 2:1-4'], ARRAY['Juan 14:26'], ARRAY['Espíritu Santo', 'presencia de Dios'], ARRAY['Espíritu Santo'], ARRAY['pneumatología'], ARRAY['culto dominical', 'momento de oración', 'altar'], ARRAY['todo público'], 1560, true, true),

('https://open.spotify.com/track/ejemplo6', 'spotify', 'Porque De Tal Manera', 'Miel San Marcos', 'Canción basada en Juan 3:16', '4:15', 'musica', 'adoracion', 'pop_cristiano', true, true, 'adoracion_profunda', 'media', 'basico', 95, 90, 82, 93, 92, 90, true, 'Basada directamente en Juan 3:16. Mensaje claro del evangelio.', ARRAY['Juan 3:16'], ARRAY['Juan 3:16'], ARRAY['amor de Dios', 'sacrificio', 'salvación'], ARRAY['Jesús'], ARRAY['soteriología'], ARRAY['culto dominical', 'evangelismo'], ARRAY['todo público', 'nuevos creyentes'], 4230, true, true),

('https://open.spotify.com/track/ejemplo7', 'spotify', 'Firme y Adelante', 'Himnario Cristiano', 'Himno clásico de la iglesia cristiana', '3:15', 'musica', 'alabanza', 'himnos_clasicos', true, true, 'apertura', 'alta', 'basico', 88, 92, 80, 90, 95, 89, true, 'Himno clásico con doctrina sólida.', ARRAY['Efesios 6:10-18'], ARRAY['Efesios 6:10'], ARRAY['perseverancia', 'fe', 'valentía'], ARRAY[]::TEXT[], ARRAY['eclesiología'], ARRAY['culto dominical', 'apertura de servicio'], ARRAY['todo público'], 980, true, true),

('https://open.spotify.com/track/ejemplo8', 'spotify', 'Avívanos', 'New Wine', 'Reggaetón cristiano con mensaje de avivamiento', '3:50', 'musica', 'alabanza', 'reggaeton_cristiano', false, true, 'alabanza_energica', 'alta', 'basico', 82, 78, 70, 85, 80, 79, true, 'Ritmo urbano con mensaje de avivamiento.', ARRAY['Hechos 2:1-4', 'Habacuc 3:2'], ARRAY['Habacuc 3:2'], ARRAY['avivamiento', 'Espíritu Santo'], ARRAY['Espíritu Santo'], ARRAY['pneumatología'], ARRAY['grupo de jóvenes', 'evento juvenil'], ARRAY['jóvenes'], 3200, true, true),

('https://open.spotify.com/track/ejemplo11', 'spotify', 'Renuévame', 'Marcos Witt', 'Balada de entrega y renovación espiritual', '4:32', 'musica', 'adoracion', 'balada_cristiana', true, true, 'altar', 'baja', 'basico', 90, 85, 78, 93, 88, 87, true, 'Balada de consagración. Letra de entrega genuina.', ARRAY['Salmo 51:10-12', 'Romanos 12:1-2'], ARRAY['Salmo 51:10'], ARRAY['renovación', 'arrepentimiento', 'consagración'], ARRAY['David'], ARRAY['santificación'], ARRAY['altar', 'momento de oración', 'devocional personal'], ARRAY['todo público'], 2890, true, true),

('https://www.youtube.com/watch?v=ejemplo12', 'youtube', 'Tu Fidelidad', 'Marcos Witt', 'Grande es tu fidelidad, oh Dios', '5:01', 'musica', 'adoracion', 'worship', true, true, 'adoracion_profunda', 'media', 'basico', 88, 95, 82, 94, 93, 90, true, 'Basada en Lamentaciones 3:22-23. Doctrina sólida sobre la fidelidad de Dios.', ARRAY['Lamentaciones 3:22-23'], ARRAY['Lamentaciones 3:23'], ARRAY['fidelidad de Dios', 'misericordia', 'confianza'], ARRAY['Jeremías'], ARRAY['teología propia'], ARRAY['culto dominical', 'devocional personal'], ARRAY['todo público'], 3450, true, true);

-- ===== ENSEÑANZAS Y PREDICACIONES =====
INSERT INTO contenido (url, plataforma, titulo, artista, descripcion, duracion, tipo, categoria, genero_musical, es_congregacional, tiene_mensaje, momento_del_culto, energia, nivel, eval_cristocentrico, eval_fidelidad_biblica, eval_profundidad, eval_edificante, eval_doctrina_sana, eval_puntuacion_total, eval_aprobado, eval_notas, pasajes, versiculos_clave, temas, personajes, doctrina, apto_para, audiencia, likes, publicado, revisado_por_ia) VALUES
('https://www.youtube.com/watch?v=ejemplo5', 'youtube', 'El Amor Incondicional de Dios - Juan 3:16', 'Pastor Juan Castellanos', 'Predicación evangelística sobre el versículo más conocido de la Biblia.', '38:00', 'predicacion', 'evangelistico', NULL, false, true, 'predica', 'alta', 'basico', 98, 92, 85, 95, 93, 93, true, 'Predicación evangelística poderosa centrada en Juan 3:16.', ARRAY['Juan 3:16-17', 'Romanos 5:8', 'Romanos 8:38-39'], ARRAY['Juan 3:16'], ARRAY['amor de Dios', 'salvación', 'evangelio', 'vida eterna'], ARRAY['Jesús', 'Nicodemo'], ARRAY['soteriología'], ARRAY['culto dominical', 'evangelismo', 'grupo pequeño'], ARRAY['nuevos creyentes', 'no creyentes', 'todo público'], 5670, true, true),

('https://www.youtube.com/watch?v=ejemplo13', 'youtube', 'La Fe que Mueve Montañas', 'Pastor Andrés Corson', 'Predicación sobre la fe genuina basada en Hebreos 11.', '42:00', 'predicacion', 'motivacional', NULL, false, true, 'predica', 'alta', 'intermedio', 90, 93, 88, 95, 91, 91, true, 'Excelente predicación sobre la fe. Fiel al contexto de Hebreos 11.', ARRAY['Hebreos 11:1-40', 'Mateo 17:20'], ARRAY['Hebreos 11:1', 'Hebreos 11:6'], ARRAY['fe', 'confianza en Dios', 'perseverancia', 'héroes de la fe'], ARRAY['Abraham', 'Moisés', 'Sara', 'Rahab'], ARRAY['soteriología', 'santificación'], ARRAY['culto dominical', 'grupo pequeño', 'retiro'], ARRAY['todo público'], 4320, true, true),

('https://www.youtube.com/watch?v=ejemplo14', 'youtube', 'El Poder de la Oración', 'Apóstol Guillermo Maldonado', 'Enseñanza sobre los diferentes tipos de oración y su poder transformador.', '35:00', 'predicacion', 'doctrina', NULL, false, true, 'predica', 'media', 'intermedio', 85, 82, 80, 88, 78, 83, true, 'Enseñanza práctica sobre oración. Algunos puntos podrían profundizarse bíblicamente.', ARRAY['Mateo 6:5-15', 'Santiago 5:16', '1 Tesalonicenses 5:17'], ARRAY['Santiago 5:16', 'Filipenses 4:6'], ARRAY['oración', 'intercesión', 'vida devocional'], ARRAY['Jesús', 'Elías'], ARRAY['oración'], ARRAY['culto dominical', 'grupo pequeño', 'retiro de oración'], ARRAY['todo público'], 3890, true, true),

('https://www.youtube.com/watch?v=ejemplo10', 'youtube', 'Reflexión Matutina: La Paz de Dios', 'Pastora María López', 'Devocional sobre Filipenses 4:6-7.', '12:00', 'podcast', 'devocional', NULL, false, true, NULL, 'baja', 'basico', 88, 90, 75, 95, 92, 88, true, 'Devocional cálido y pastoral. Fiel al texto de Filipenses.', ARRAY['Filipenses 4:6-7', 'Mateo 6:25-34'], ARRAY['Filipenses 4:6-7'], ARRAY['paz', 'ansiedad', 'oración', 'confianza en Dios'], ARRAY['Pablo'], ARRAY['soteriología práctica'], ARRAY['devocional personal', 'inicio del día'], ARRAY['todo público'], 2100, true, true),

('https://www.youtube.com/watch?v=ejemplo15', 'youtube', 'Identidad en Cristo: Quién Dice Dios que Eres', 'Dr. David Cho', 'Predicación sobre la identidad del creyente según las Escrituras.', '48:00', 'predicacion', 'doctrina', NULL, false, true, 'predica', 'media', 'intermedio', 94, 91, 90, 96, 92, 93, true, 'Excelente enseñanza sobre identidad en Cristo. Sólidamente bíblica.', ARRAY['Efesios 1:3-14', '2 Corintios 5:17', 'Gálatas 2:20'], ARRAY['2 Corintios 5:17', 'Efesios 1:4-5'], ARRAY['identidad en Cristo', 'nueva creación', 'adopción', 'propósito'], ARRAY['Pablo'], ARRAY['soteriología', 'cristología'], ARRAY['culto dominical', 'grupo pequeño', 'consejería'], ARRAY['todo público', 'nuevos creyentes'], 6120, true, true),

('https://www.youtube.com/watch?v=ejemplo16', 'youtube', 'Cómo Leer la Biblia: Guía para Principiantes', 'Pastor José Martínez', 'Guía práctica para comenzar a leer y entender la Biblia.', '25:00', 'podcast', 'devocional', NULL, false, true, NULL, 'media', 'basico', 86, 94, 80, 92, 95, 89, true, 'Guía excelente para nuevos creyentes. Hermenéutica básica bien explicada.', ARRAY['2 Timoteo 3:16-17', 'Salmo 119:105'], ARRAY['2 Timoteo 3:16'], ARRAY['estudio bíblico', 'hermenéutica', 'lectura bíblica'], ARRAY['Timoteo', 'Pablo'], ARRAY['bibliología'], ARRAY['discipulado', 'nuevos creyentes', 'grupo pequeño'], ARRAY['nuevos creyentes', 'todo público'], 3560, true, true);

-- ===== ESTUDIOS BÍBLICOS =====
INSERT INTO contenido (url, plataforma, titulo, artista, descripcion, duracion, tipo, categoria, genero_musical, es_congregacional, tiene_mensaje, momento_del_culto, energia, nivel, eval_cristocentrico, eval_fidelidad_biblica, eval_profundidad, eval_edificante, eval_doctrina_sana, eval_puntuacion_total, eval_aprobado, eval_notas, pasajes, versiculos_clave, temas, personajes, doctrina, apto_para, audiencia, likes, publicado, revisado_por_ia) VALUES
('https://www.youtube.com/watch?v=ejemplo3', 'youtube', 'Juan 3: El Nuevo Nacimiento - Estudio Expositivo', 'Pastor Andrés Corson', 'Estudio verso por verso de Juan 3. La conversación de Jesús con Nicodemo.', '45:00', 'estudio_biblico', 'doctrina', NULL, false, true, NULL, 'media', 'intermedio', 97, 95, 92, 90, 96, 94, true, 'Estudio expositivo excelente. Fiel al contexto de Juan 3.', ARRAY['Juan 3:1-21'], ARRAY['Juan 3:3', 'Juan 3:16', 'Juan 3:5-6'], ARRAY['nuevo nacimiento', 'regeneración', 'salvación', 'fe', 'vida eterna'], ARRAY['Jesús', 'Nicodemo'], ARRAY['soteriología', 'regeneración'], ARRAY['grupo pequeño', 'estudio bíblico', 'preparación de sermón'], ARRAY['líderes', 'todo público'], 3450, true, true),

('https://www.youtube.com/watch?v=ejemplo9', 'youtube', 'Romanos 8: Más que Vencedores', 'Dr. David Cho', 'Estudio profundo de Romanos 8. No hay condenación para los que están en Cristo.', '52:00', 'estudio_biblico', 'doctrina', NULL, false, true, NULL, 'media', 'avanzado', 96, 97, 95, 93, 95, 95, true, 'Estudio expositivo de alto nivel. Excelente fidelidad al texto.', ARRAY['Romanos 8:1-39'], ARRAY['Romanos 8:1', 'Romanos 8:28', 'Romanos 8:37-39'], ARRAY['justificación', 'vida en el Espíritu', 'victoria', 'amor de Dios'], ARRAY['Jesús', 'Espíritu Santo'], ARRAY['soteriología', 'pneumatología'], ARRAY['estudio bíblico', 'seminario', 'preparación de sermón'], ARRAY['líderes', 'pastores', 'estudiantes de teología'], 4500, true, true),

('https://www.youtube.com/watch?v=ejemplo17', 'youtube', 'Salmo 23: El Buen Pastor', 'Dra. Ana Torres', 'Estudio detallado del Salmo 23, verso por verso con contexto histórico.', '40:00', 'estudio_biblico', 'devocional', NULL, false, true, NULL, 'baja', 'basico', 92, 96, 88, 97, 95, 94, true, 'Estudio hermoso del Salmo 23. Conecta con Cristo como el Buen Pastor.', ARRAY['Salmo 23:1-6', 'Juan 10:11-14'], ARRAY['Salmo 23:1', 'Salmo 23:4', 'Juan 10:11'], ARRAY['protección divina', 'provisión', 'confianza', 'el buen pastor'], ARRAY['David', 'Jesús'], ARRAY['cristología', 'providencia'], ARRAY['devocional personal', 'grupo pequeño', 'consejería'], ARRAY['todo público'], 5200, true, true),

('https://www.youtube.com/watch?v=ejemplo18', 'youtube', 'Gálatas: Libertad en Cristo', 'Teólogo Carlos Ramírez', 'Panorama completo de la carta a los Gálatas. Gracia vs legalismo.', '55:00', 'estudio_biblico', 'doctrina', NULL, false, true, NULL, 'media', 'avanzado', 95, 96, 94, 88, 97, 94, true, 'Estudio magistral de Gálatas. Claridad excepcional sobre gracia vs ley.', ARRAY['Gálatas 1-6'], ARRAY['Gálatas 2:20', 'Gálatas 5:1', 'Gálatas 3:28'], ARRAY['libertad en Cristo', 'gracia', 'legalismo', 'justificación por fe'], ARRAY['Pablo', 'Pedro'], ARRAY['soteriología', 'eclesiología'], ARRAY['seminario', 'estudio bíblico', 'preparación de sermón'], ARRAY['líderes', 'pastores', 'estudiantes de teología'], 3890, true, true);

-- ===== COMUNIDADES =====
INSERT INTO comunidades (nombre, descripcion, imagen, tipo) VALUES
('Iglesia Central Medellín', 'Comunidad principal de adoración y enseñanza', '⛪', 'iglesia'),
('Grupo Jóvenes Fe', 'Jóvenes apasionados por Cristo', '🔥', 'jovenes'),
('Banda de Adoración', 'Músicos y adoradores unidos', '🎸', 'banda'),
('Oración 24/7', 'Intercesión continua por las naciones', '🙏', 'oracion'),
('Estudio Romanos', 'Estudio semanal del libro de Romanos', '📖', 'grupo_estudio'),
('Matrimonios Bendecidos', 'Familias creciendo en la fe', '💑', 'iglesia');

-- ===== GUÍAS DE ESTUDIO =====
INSERT INTO guias_estudio (pasaje_principal, titulo, contexto, versiculos_clave, temas_relacionados, pasajes_conectados, preguntas_reflexion, aplicacion_practica) VALUES
('Juan 3', 'Jesús y Nicodemo: El Nuevo Nacimiento', 'Juan 3 relata la visita nocturna de Nicodemo, un fariseo y miembro del concilio judío, a Jesús. En esta conversación, Jesús enseña sobre la necesidad de nacer de nuevo por el Espíritu Santo para entrar en el reino de Dios. El pasaje culmina con Juan 3:16, el versículo más conocido de toda la Biblia.', ARRAY['Juan 3:3', 'Juan 3:5-6', 'Juan 3:16', 'Juan 3:17', 'Juan 3:36'], ARRAY['nuevo nacimiento', 'gracia', 'salvación', 'fe', 'vida eterna', 'amor de Dios'], ARRAY['Romanos 6:23', 'Efesios 2:8-9', 'Tito 3:5', '1 Pedro 1:3', 'Romanos 8:1'], ARRAY['¿Qué significa nacer de nuevo?', '¿Por qué Nicodemo no entendía?', '¿Cómo se conecta Juan 3:16 con tu vida?', '¿Qué rol juega el Espíritu Santo en el nuevo nacimiento?'], ARRAY['Medita en Juan 3:16 esta semana', 'Comparte el evangelio con alguien', 'Ora por quienes aún no conocen a Cristo']),

('Romanos 8', 'Vida en el Espíritu: Más que Vencedores', 'Romanos 8 es considerado uno de los capítulos más importantes de toda la Biblia. Pablo explica que no hay condenación para los que están en Cristo, describe la vida guiada por el Espíritu Santo, y concluye con una de las declaraciones más poderosas sobre el amor inseparable de Dios.', ARRAY['Romanos 8:1', 'Romanos 8:28', 'Romanos 8:31', 'Romanos 8:37-39'], ARRAY['justificación', 'Espíritu Santo', 'victoria', 'amor de Dios', 'predestinación'], ARRAY['Romanos 5:1-5', 'Gálatas 5:16-25', 'Efesios 1:3-14', 'Juan 16:7-15'], ARRAY['¿Qué significa no hay condenación?', '¿Cómo vives guiado por el Espíritu?', '¿De qué eres más que vencedor?', '¿Qué puede separarte del amor de Dios?'], ARRAY['Memoriza Romanos 8:28', 'Identifica áreas de condenación y entrégalas a Cristo', 'Ora pidiendo la guía del Espíritu Santo']),

('Salmo 23', 'El Señor es Mi Pastor: Protección y Provisión', 'El Salmo 23 es quizás el salmo más amado de toda la Biblia. David, quien fue pastor antes de ser rey, usa la metáfora del pastor y sus ovejas para describir la relación íntima entre Dios y su pueblo. Cada verso revela un aspecto diferente del cuidado de Dios.', ARRAY['Salmo 23:1', 'Salmo 23:4', 'Salmo 23:6'], ARRAY['protección', 'provisión', 'confianza', 'el buen pastor', 'paz'], ARRAY['Juan 10:11-14', 'Isaías 40:11', 'Ezequiel 34:11-16', '1 Pedro 5:7'], ARRAY['¿En qué áreas necesitas que Dios sea tu pastor?', '¿Qué valle estás atravesando ahora?', '¿Cómo experimentas la bondad de Dios?', '¿Confías en que nada te faltará?'], ARRAY['Lee el Salmo 23 cada mañana esta semana', 'Haz una lista de cómo Dios ha provisto para ti', 'Ora el Salmo 23 personalizándolo con tu situación']);

-- ===== BOT LOG INICIAL =====
INSERT INTO bot_log (tipo, estado, descripcion, resultado, completed_at) VALUES
('descubrir', 'completado', 'Escaneó 50 videos nuevos en YouTube sobre adoración 2024', '12 aprobados, 38 rechazados', now()),
('clasificar', 'completado', 'Clasificó 18 contenidos nuevos con IA teológica', '16 publicados, 2 requieren revisión manual', now()),
('generar_guia', 'completado', 'Generó guía de estudio para Juan 3, Romanos 8 y Salmo 23', '3 guías publicadas con contenido relacionado', now()),
('analizar_tendencias', 'completado', 'Analizó tendencias de la última semana', 'Tema trending: identidad en Cristo (+340% búsquedas)', now()),
('descubrir', 'procesando', 'Buscando nuevas predicaciones sobre Espíritu Santo en YouTube...', NULL, NULL);
